### ISSUE TITLE
ライブラリ名及びコマンドについて

### ISSUE THREAD

**Issue by ghost** [wadahiro/go-transproxy#2]
`package tproxy` とするのであればリポジトリを `go-transproxy` とするのではなく `tproxy` か `go-tproxy` にしたほうがいいのではないでしょうか？
- <http://golang-jp.org/doc/code.html#PackageNames>

またコマンドについてですが `go-transproxy` だと長いので `tproxy` か `transproxy` のようにしてほしいです

**Comment by wadahiro** [comment]
>package tproxy とするのであればリポジトリを go-transproxy とするのではなく tproxy か go-tproxy にしたほうがいいのではないでしょうか？

ご指摘ありがとうございます。
最初は go-tproxy だったのですが、 [同名](https://github.com/LiamHaworth/go-tproxy) があることに途中で気づいてリポジトリ名を変更したという経緯があります。
これはパッケージ名の修正漏れなので、 `package transproxy` に修正したいと思います。

>またコマンドについてですが go-transproxy だと長いので tproxy か transproxy のようにしてほしいです

そうですね、`transproxy` にしたいと思います！
